services:
  frontend:
    #image: httpd:latest
    build: ./frontend/
    container_name: frontend
    environment:
      API_HOST: "http://localhost:5000/build"
      API_KEY: "a1b2c3d4e5f6g7"
    ports:
    - 8280:80

  backend:
    build: ./backend/
    container_name: backend
    volumes:
    - ./backend/app.py:/usr/src/myapp/app.py:Z
    command: python /usr/src/myapp/app.py
    ports:
    - 5000:5000
